import type { HomeAssistant } from "./types";

type Dict = Record<string, string>;

// Pulse wording is shared with Area Pulse Card on purpose: "1 window open" reads the same on both cards.
const en: Dict = {
  greet_morning: "Good morning",
  greet_afternoon: "Good afternoon",
  greet_evening: "Good evening",
  greet_night: "Good night",
  greet_with_name: "{greet}, {name}",
  home: "Home",
  away: "Away",

  alarm_disarmed: "Disarmed",
  alarm_armed_home: "Armed home",
  alarm_armed_away: "Armed away",
  alarm_armed_night: "Armed night",
  alarm_armed_vacation: "Armed vacation",
  alarm_armed_custom_bypass: "Armed custom",
  alarm_arming: "Arming",
  alarm_pending: "Pending",
  alarm_disarming: "Disarming",
  alarm_triggered: "Triggered",
  alarm_btn_arm_home: "Home",
  alarm_btn_arm_away: "Away",
  alarm_btn_arm_night: "Night",
  alarm_btn_arm_vacation: "Vacation",
  alarm_btn_arm_custom_bypass: "Custom",
  alarm_btn_disarm: "Disarm",
  just_now: "just now",
  today_today: "today",
  today_tomorrow: "tomorrow",
  today_until: "until {time}",

  door_open: "{n} door open",
  doors_open: "{n} doors open",
  doors_closed: "Doors closed",
  window_open: "{n} window open",
  windows_open: "{n} windows open",
  windows_closed: "Windows closed",
  cover_open: "{n} cover open",
  covers_open_n: "{n} covers open",
  covers_closed: "Covers closed",
  lock_unlocked: "{n} unlocked",
  locks_locked: "Locked",
  light_on: "{n} light on",
  lights_on_n: "{n} lights on",
  lights_off_all: "Lights off",
  fan_on: "{n} fan on",
  fans_on_n: "{n} fans on",
  fans_off_all: "Fans off",
  switch_on: "{n} switch on",
  switches_on_n: "{n} switches on",
  switches_off_all: "Switches off",
  media_playing_n: "{n} playing",
  media_idle: "Media idle",
  climate_on: "{n} climate running",
  climate_on_n: "{n} climate running",
  climate_off: "Climate off",
  alert: "Alert",
  alerts_n: "{n} alerts",
  alerts_none: "No alerts",
  battery_low: "{n} low battery",
  batteries_low: "{n} low batteries",
  batteries_ok: "Batteries OK",
  all_quiet: "All quiet",

  nudge_nobody_home: "Nobody's home",
  nudge_away_alarm: "Alarm is off",
  nudge_fix_lights: "Lights off",
  nudge_fix_media: "Pause media",
  nudge_fix_alarm: "Arm away",
  nudge_unlocked: "{n} lock unlocked",
  nudge_unlocked_n: "{n} locks unlocked",
  nudge_fix_locks: "Lock",
  nudge_fix_doors: "Show doors",
  nudge_fix_windows: "Show windows",
  weather_range: "High {high}, low {low}",
  weather_high: "High {high}",
  shortcuts_empty: "Add shortcuts in the card editor",
  ed_shortcuts_own_card: "Shortcuts have their own card: add a “Home Pulse Shortcuts” card next to this one.",
  ed_shortcuts_move: "These shortcuts keep working here. To give them their own card, add a “Home Pulse Shortcuts” card and move them there.",
  ed_appearance_tiles: "Separate tiles (like native tile cards)",
  ed_appearance_one_card: "All in one card",

  g_alerts: "Safety alerts",
  g_lights: "Lights",
  g_doors: "Doors",
  g_windows: "Windows",
  g_covers: "Covers",
  g_locks: "Locks",
  g_fans: "Fans",
  g_switches: "Switches & plugs",
  g_media: "Media",
  g_climate: "Climate",
  g_batteries: "Batteries",
  n_of_m_active: "{n} of {m} active",
  no_area: "No area",
  turn_all_on: "All on",
  turn_all_off: "All off",
  open_all: "Open all",
  close_all: "Close all",
  lock_all: "Lock all",
  pause_all: "Pause all",
  close: "Close",

  ed_section_greeting: "Greeting",
  ed_section_status: "People, weather & chips",
  ed_section_alarm: "Alarm",
  ed_section_modes: "House modes",
  ed_sec_modes: "House modes",
  ed_mode_entity: "Mode selector (input_select or select)",
  ed_modes_hint: "Pick a mode selector to get one button per option, or add modes that run a scene, a script or any action.",
  ed_modes_hint_auto: "One button per option of the selector. Add modes here to rename, reorder or pick icons and colours.",
  ed_add_mode: "Add mode",
  ed_mode_n: "Mode {n}",
  ed_option: "Option it selects (default: the name)",
  ed_today_show: "Today line under the date",
  ed_today_tomorrow: "Include tomorrow",
  ed_today_calendars: "Calendars (empty = all)",
  ed_today_entities: "Extra sensors (waste collection, dates, text)",
  ed_section_pulse: "Home pulse",
  ed_section_shortcuts: "Shortcuts",
  ed_sections: "Blocks to show, in order",
  ed_sec_greeting: "Greeting",
  ed_sec_status: "People & alarm",
  ed_sec_alerts: "Safety alerts (only when one trips)",
  ed_sec_nudges: "Nobody's home hints (only when needed)",
  ed_sec_alarm: "Alarm panel with buttons",
  ed_sec_pulse: "Home pulse (lights, windows, …)",
  ed_sec_shortcuts: "Shortcuts",
  ed_layout: "Layout",
  ed_layout_default: "Default",
  ed_layout_compact: "Compact",
  ed_appearance: "Appearance",
  ed_appearance_card: "Card",
  ed_appearance_flat: "Flat (no background)",
  ed_title: "Greeting text ({name} = your first name)",
  ed_show_date: "Show today's date",
  ed_center_greeting: "Centre the greeting",
  ed_persons: "People (empty = everyone)",
  ed_show_away: "Show people who are away",
  ed_weather_entity: "Weather",
  ed_alarm_entity: "Alarm panel",
  ed_alarm_modes: "Arm buttons",
  ed_pulse: "Groups, in order",
  ed_show_inactive: "Show groups with nothing active",
  ed_nudges: "Hints when nobody is home",
  ed_alert_classes: "Alert device classes",
  ed_exclude_entities: "Exclude entities",
  ed_battery_threshold: "Low battery threshold (%)",
  ed_columns: "Tiles per row",
  ed_show_names: "Show names under icons",
  ed_add_shortcut: "Add shortcut",
  ed_shortcut_n: "Shortcut {n}",
  ed_name: "Name",
  ed_icon: "Icon",
  ed_color: "Icon colour",
  ed_navigation_path: "Open view (e.g. lights or /lovelace/lights)",
  ed_entity: "Entity (tints the tile when on)",
  ed_badge: "Badge",
  ed_badge_none: "None",
  ed_badge_entity: "Badge from entity state",
  ed_tap_action: "Tap action (overrides the view)",
  ed_hold_action: "Hold action",
  ed_double_tap_action: "Double tap action",
  ed_remove: "Remove",
  ed_move_up: "Move up",
  ed_move_down: "Move down",
  ed_none: "None",
  ed_auto: "Automatic",
  ed_chips_yaml: "Extra chips are set in YAML (chips:). See the README.",
};

const el: Dict = {
  greet_morning: "Καλημέρα",
  greet_afternoon: "Καλό απόγευμα",
  greet_evening: "Καλησπέρα",
  greet_night: "Καληνύχτα",
  greet_with_name: "{greet}, {name}",
  home: "Σπίτι",
  away: "Εκτός",

  alarm_disarmed: "Αφοπλισμένος",
  alarm_armed_home: "Οπλισμένος (σπίτι)",
  alarm_armed_away: "Οπλισμένος (εκτός)",
  alarm_armed_night: "Οπλισμένος (νύχτα)",
  alarm_armed_vacation: "Οπλισμένος (διακοπές)",
  alarm_armed_custom_bypass: "Οπλισμένος (προσαρμ.)",
  alarm_arming: "Όπλιση",
  alarm_pending: "Σε αναμονή",
  alarm_disarming: "Αφόπλιση",
  alarm_triggered: "Ενεργοποιήθηκε",
  alarm_btn_arm_home: "Σπίτι",
  alarm_btn_arm_away: "Εκτός",
  alarm_btn_arm_night: "Νύχτα",
  alarm_btn_arm_vacation: "Διακοπές",
  alarm_btn_arm_custom_bypass: "Προσαρμ.",
  alarm_btn_disarm: "Αφόπλιση",
  just_now: "μόλις τώρα",
  today_today: "σήμερα",
  today_tomorrow: "αύριο",
  today_until: "έως {time}",

  door_open: "{n} πόρτα ανοιχτή",
  doors_open: "{n} πόρτες ανοιχτές",
  doors_closed: "Πόρτες κλειστές",
  window_open: "{n} παράθυρο ανοιχτό",
  windows_open: "{n} παράθυρα ανοιχτά",
  windows_closed: "Παράθυρα κλειστά",
  cover_open: "{n} ρολό ανοιχτό",
  covers_open_n: "{n} ρολά ανοιχτά",
  covers_closed: "Ρολά κλειστά",
  lock_unlocked: "{n} ξεκλείδωτη",
  locks_locked: "Κλειδωμένα",
  light_on: "{n} φως αναμμένο",
  lights_on_n: "{n} φώτα αναμμένα",
  lights_off_all: "Φώτα σβηστά",
  fan_on: "{n} ανεμιστήρας",
  fans_on_n: "{n} ανεμιστήρες",
  fans_off_all: "Ανεμιστήρες off",
  switch_on: "{n} διακόπτης on",
  switches_on_n: "{n} διακόπτες on",
  switches_off_all: "Διακόπτες off",
  media_playing_n: "{n} σε αναπαραγωγή",
  media_idle: "Media σε αδράνεια",
  climate_on: "{n} κλιματισμός σε λειτουργία",
  climate_on_n: "{n} κλιματισμοί σε λειτουργία",
  climate_off: "Κλιματισμός off",
  alert: "Συναγερμός",
  alerts_n: "{n} ειδοποιήσεις",
  alerts_none: "Καμία ειδοποίηση",
  battery_low: "{n} χαμηλή μπαταρία",
  batteries_low: "{n} χαμηλές μπαταρίες",
  batteries_ok: "Μπαταρίες εντάξει",
  all_quiet: "Όλα ήσυχα",

  nudge_nobody_home: "Δεν είναι κανείς σπίτι",
  nudge_away_alarm: "Ο συναγερμός είναι κλειστός",
  nudge_fix_lights: "Σβήσε τα φώτα",
  nudge_fix_media: "Παύση media",
  nudge_fix_alarm: "Όπλιση εκτός",
  nudge_unlocked: "{n} κλειδαριά ξεκλείδωτη",
  nudge_unlocked_n: "{n} κλειδαριές ξεκλείδωτες",
  nudge_fix_locks: "Κλείδωσε",
  nudge_fix_doors: "Δες τις πόρτες",
  nudge_fix_windows: "Δες τα παράθυρα",
  weather_range: "Μέγιστη {high}, ελάχιστη {low}",
  weather_high: "Μέγιστη {high}",
  shortcuts_empty: "Πρόσθεσε συντομεύσεις από τον επεξεργαστή της κάρτας",
  ed_shortcuts_own_card: "Οι συντομεύσεις έχουν δική τους κάρτα: πρόσθεσε μια κάρτα «Home Pulse Shortcuts» δίπλα σε αυτή.",
  ed_shortcuts_move: "Αυτές οι συντομεύσεις συνεχίζουν να δουλεύουν εδώ. Για δική τους κάρτα, πρόσθεσε μια κάρτα «Home Pulse Shortcuts» και μετάφερέ τες εκεί.",
  ed_appearance_tiles: "Ξεχωριστά πλακίδια (όπως οι εγγενείς κάρτες tile)",
  ed_appearance_one_card: "Όλα σε μία κάρτα",

  g_alerts: "Ειδοποιήσεις ασφαλείας",
  g_lights: "Φώτα",
  g_doors: "Πόρτες",
  g_windows: "Παράθυρα",
  g_covers: "Ρολά",
  g_locks: "Κλειδαριές",
  g_fans: "Ανεμιστήρες",
  g_switches: "Διακόπτες & πρίζες",
  g_media: "Media",
  g_climate: "Κλιματισμός",
  g_batteries: "Μπαταρίες",
  n_of_m_active: "{n} από {m} ενεργά",
  no_area: "Χωρίς χώρο",
  turn_all_on: "Όλα on",
  turn_all_off: "Όλα off",
  open_all: "Άνοιγμα όλων",
  close_all: "Κλείσιμο όλων",
  lock_all: "Κλείδωμα όλων",
  pause_all: "Παύση όλων",
  close: "Κλείσιμο",

  ed_section_greeting: "Χαιρετισμός",
  ed_section_status: "Άτομα, καιρός & chips",
  ed_section_alarm: "Συναγερμός",
  ed_section_modes: "Λειτουργίες σπιτιού",
  ed_sec_modes: "Λειτουργίες σπιτιού",
  ed_mode_entity: "Επιλογέας λειτουργίας (input_select ή select)",
  ed_modes_hint: "Διάλεξε επιλογέα για ένα κουμπί ανά επιλογή, ή πρόσθεσε λειτουργίες που τρέχουν σκηνή, script ή οποιαδήποτε ενέργεια.",
  ed_modes_hint_auto: "Ένα κουμπί ανά επιλογή του επιλογέα. Πρόσθεσε λειτουργίες εδώ για μετονομασία, σειρά, εικονίδια και χρώματα.",
  ed_add_mode: "Προσθήκη λειτουργίας",
  ed_mode_n: "Λειτουργία {n}",
  ed_option: "Επιλογή που ενεργοποιεί (προεπιλογή: το όνομα)",
  ed_today_show: "Γραμμή «Σήμερα» κάτω από την ημερομηνία",
  ed_today_tomorrow: "Και τα αυριανά",
  ed_today_calendars: "Ημερολόγια (κενό = όλα)",
  ed_today_entities: "Επιπλέον αισθητήρες (απορρίμματα, ημερομηνίες, κείμενο)",
  ed_section_pulse: "Παλμός σπιτιού",
  ed_section_shortcuts: "Συντομεύσεις",
  ed_sections: "Τμήματα προς εμφάνιση, με σειρά",
  ed_sec_greeting: "Χαιρετισμός",
  ed_sec_status: "Άτομα & συναγερμός",
  ed_sec_alerts: "Ειδοποιήσεις ασφαλείας (μόνο όταν ενεργοποιηθούν)",
  ed_sec_nudges: "Υποδείξεις όταν δεν είναι κανείς σπίτι (μόνο όταν χρειάζεται)",
  ed_sec_alarm: "Πίνακας συναγερμού με κουμπιά",
  ed_sec_pulse: "Παλμός σπιτιού (φώτα, παράθυρα, …)",
  ed_sec_shortcuts: "Συντομεύσεις",
  ed_layout: "Διάταξη",
  ed_layout_default: "Κανονική",
  ed_layout_compact: "Συμπαγής",
  ed_appearance: "Εμφάνιση",
  ed_appearance_card: "Κάρτα",
  ed_appearance_flat: "Επίπεδη (χωρίς φόντο)",
  ed_title: "Κείμενο χαιρετισμού ({name} = το μικρό σου όνομα)",
  ed_show_date: "Εμφάνιση σημερινής ημερομηνίας",
  ed_center_greeting: "Χαιρετισμός στο κέντρο",
  ed_persons: "Άτομα (κενό = όλοι)",
  ed_show_away: "Εμφάνιση όσων είναι εκτός",
  ed_weather_entity: "Καιρός",
  ed_alarm_entity: "Πίνακας συναγερμού",
  ed_alarm_modes: "Κουμπιά όπλισης",
  ed_pulse: "Ομάδες, με σειρά",
  ed_show_inactive: "Εμφάνιση ομάδων χωρίς ενεργά",
  ed_nudges: "Υποδείξεις όταν δεν είναι κανείς σπίτι",
  ed_alert_classes: "Κλάσεις συσκευών ειδοποίησης",
  ed_exclude_entities: "Εξαίρεση οντοτήτων",
  ed_battery_threshold: "Όριο χαμηλής μπαταρίας (%)",
  ed_columns: "Πλακίδια ανά σειρά",
  ed_show_names: "Ονόματα κάτω από τα εικονίδια",
  ed_add_shortcut: "Προσθήκη συντόμευσης",
  ed_shortcut_n: "Συντόμευση {n}",
  ed_name: "Όνομα",
  ed_icon: "Εικονίδιο",
  ed_color: "Χρώμα εικονιδίου",
  ed_navigation_path: "Άνοιγμα προβολής (π.χ. lights ή /lovelace/lights)",
  ed_entity: "Οντότητα (χρωματίζει το πλακίδιο όταν είναι on)",
  ed_badge: "Σήμα",
  ed_badge_none: "Κανένα",
  ed_badge_entity: "Σήμα από κατάσταση οντότητας",
  ed_tap_action: "Ενέργεια πατήματος (αντί για την προβολή)",
  ed_hold_action: "Ενέργεια παρατεταμένου πατήματος",
  ed_double_tap_action: "Ενέργεια διπλού πατήματος",
  ed_remove: "Αφαίρεση",
  ed_move_up: "Πάνω",
  ed_move_down: "Κάτω",
  ed_none: "Κανένα",
  ed_auto: "Αυτόματα",
  ed_chips_yaml: "Τα επιπλέον chips ορίζονται σε YAML (chips:). Δες το README.",
};

const LANGS: Record<string, Dict> = { en, el };

export function localize(
  hass: HomeAssistant | undefined,
  key: string,
  vars: Record<string, string | number> = {}
): string {
  const lang = language(hass);
  let s = LANGS[lang]?.[key] ?? en[key] ?? key;
  for (const [k, v] of Object.entries(vars)) s = s.replace(`{${k}}`, String(v));
  return s;
}

export function language(hass?: HomeAssistant): string {
  return (hass?.locale?.language || hass?.language || "en").split("-")[0];
}

/** "3 days ago", "in 5 min", localised by the browser. */
export function relativeTime(hass: HomeAssistant | undefined, iso: string, now = Date.now()): string {
  const t = Date.parse(iso);
  if (Number.isNaN(t)) return "";
  const secs = Math.round((t - now) / 1000);
  if (Math.abs(secs) < 45) return localize(hass, "just_now");
  const fmt = new Intl.RelativeTimeFormat(hass?.locale?.language || hass?.language || "en", { numeric: "auto" });
  const units: [Intl.RelativeTimeFormatUnit, number][] = [
    ["day", 86400],
    ["hour", 3600],
    ["minute", 60],
  ];
  for (const [unit, size] of units) if (Math.abs(secs) >= size) return fmt.format(Math.round(secs / size), unit);
  return fmt.format(Math.round(secs / 60), "minute");
}
